### ISSUE TITLE
[PANEL] Ban list doesn't work

### ISSUE THREAD

**Issue by MiniDigger** [SpaceCP/Bugs#7] opened 2015-12-10 22:15 UTC
See https://gyazo.com/ea66b3e8d9c7d7d17970aa75b0b1b798
I guess this is liked to #6. the ban shows up under recent activity but does not reach the minecraft server

**Comment by jithatsonei** [comment] 2015-12-12 02:46
![image](https://cloud.githubusercontent.com/assets/12538482/11759746/4073980c-a048-11e5-9351-e358452b5f44.png)

Can't reproduce. Have you tried restarting your daemon; then server?

**Comment by MiniDigger** [comment] 2015-12-12 07:57
Someone wrote somewhere (lol) that you can ban/whitlist players who never joined the server because of uuid problems. I will try to verify that later and do some more testing

**Comment by MiniDigger** [comment] 2015-12-12 08:31
Did some testing. Can't realy confirm what I have stated above. Whitelisting seems to work better with ppl who joined the server before but banning doesn't. I can ban myself but can't pardon me... I can't even see the message from your screenshot in my console.

My daemon version is a166cb842432b9f456b2bad37b268ca9b435c8f2_1449876288_157 (thats what is written in the version.txt idk if that helps, should be build 4 since I just updated) and it is running on Debian Wheezy.
I opened the panel with win10 64bit on Chrome 47

**Comment by Antariano** [comment] 2015-12-12 13:32
What mod are you running?

**Comment by MiniDigger** [comment] 2015-12-12 20:44
Spigot 1.8.8

**Comment by Antariano** [comment] 2015-12-18 19:30
Can you confirm this is still the case?

**Comment by jithatsonei** [comment] 2015-12-18 19:34
Will test when I'm home Antariano (hour)

**Comment by MiniDigger** [comment] 2015-12-18 20:23
Will test later too

**Comment by jithatsonei** [comment] 2015-12-18 21:45
Working for me. on 1.7.4, but get this browser error on craftbukkit https://ghostbin.com/paste/vrpcd as well as spigot

**Comment by MiniDigger** [comment] 2015-12-18 21:51
It still doesn't work as expected:
If I add a player, the name is missing (tested with Test) http://puu.sh/m0zmU/e84b0833d2.png.
This is fixed by a reload.
Pardoning doesn't update either: https://gyazo.com/7fc049875f66fa362508dbbd4bc81df3
This is what the consol says:

```
spacecp.js?build=1ea469e:646 >>>> POST/api/v2/servers/5668561d7586d10242baa558/api Object {method: "pardonPlayer", data: Object, requestID: "request_33"}
spacecp.js?build=1ea469e:646 <<<< POST/api/v2/servers/5668561d7586d10242baa558/api Object {data: true, headers: Object, statusCode: 200}
```

the data object contains name: "Test". This can be fixed by a reload too.
If I try to pardon a player which I just added (without reloading, so its looking like the first screenshot) I get this error in the browser consol

```
<<<< POST/api/v2/servers/5668561d7586d10242baa558/api Object {data: Object, headers: Object, statusCode: 400}
angular.js:12416 Error: [object Object]
    at n.<anonymous> (spacecp.js?build=1ea469e:649)
    at spacecp.js?build=1ea469e:646
    at m.$eval (angular.js:15878)
    at m.$apply (angular.js:15978)
    at m.e.$safeApply (spacecp.js?build=1ea469e:663)
    at n.<anonymous> (spacecp.js?build=1ea469e:646)
    at n (spacecp.js?build=1ea469e:648)
    at n.emit [as $emit] (spacecp.js?build=1ea469e:648)
    at n.onPacket (spacecp.js?build=1ea469e:648)
    at r.onPacket (spacecp.js?build=1ea469e:648)(anonymous function) @ angular.js:12416(anonymous function) @ angular.js:9203m.$apply @ angular.js:15983e.$safeApply @ spacecp.js?build=1ea469e:663(anonymous function) @ spacecp.js?build=1ea469e:646n @ spacecp.js?build=1ea469e:648n.emit @ spacecp.js?build=1ea469e:648n.onPacket @ spacecp.js?build=1ea469e:648r.onPacket @ spacecp.js?build=1ea469e:648n.onPacket @ spacecp.js?build=1ea469e:648n.onData @ spacecp.js?build=1ea469e:648websocket.onmessage @ spacecp.js?build=1ea469e:648
```

the paron request insn't passed to the bukkit server. If I reload, the ban entry is there and I can pardon him without a problem and he can connect again. The ban entry is still showed till I reload.

**Comment by Antariano** [comment] 2015-12-18 22:43
Thank you very much, that helps

**Comment by MiniDigger** [comment] 2015-12-18 23:01
have a fun night debugging ^^

**Comment by narrowtux** [comment] 2015-12-19 15:37
You can only ban players that actually exist, because it doesn't store the actual names, but their respective UUIDs. Try banning people such as `notch`, `jeb_`, etc.

**Comment by jithatsonei** [comment] 2015-12-19 16:49
@narrowtux I used my own name for testing

**Comment by narrowtux** [comment] 2015-12-19 16:50
Yeah but you said it works for you right?

**Comment by jithatsonei** [comment] 2015-12-19 16:55
For vanilla yes, but spigot and bukkit will not. I did edit my comment about 4 minutes after I posted it stating that I got a browser error on bukkit and spigot with the following log file:  https://ghostbin.com/paste/vrpcd

**Comment by narrowtux** [comment] 2015-12-19 17:09
I tested this on my test server. The bans work, however the list in the browser doesn't update correctly. If you hit refresh, it should show the real name, and you can also check your `banned-players.json`, where the entry should appear as well. Paging @Antariano @JamyDev for possible Panel bug.

**Comment by MiniDigger** [comment] 2015-12-19 17:20
As I wrote in my comment, banning works, this is only a UI bug

**Comment by tlaundal** [comment] 2015-12-25 15:53
Here is how I experience this problem. (Tested with the new houstonbukkit.jar, not released yet)
1. When pardoning a player, only the reason shows up on the panel right away (panel problem, as houston sends the name back in an event)
2. When pardoning a player, he is not removed from the list right away. (panel problem, seems the panel doesn't subscribe to PlayerPardonEvent)
3. When reloading the page, previous pardoning and banning takes effect, as long as the player exists.
4. When reloading the page, ban reasons does not show up. I'm working on this now.

**Comment by JamyDev** [comment] 2015-12-28 18:48
Seems like this is fixed in the latest HoustonBukkit? Closing unless it's still broken.

**Closed as completed by JamyDev** 2015-12-28 18:48 UTC
