### ISSUE TITLE
RAM/CPU always shows zero - after previously working

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#70] opened 2015-12-27 03:48 UTC
it was working - but now it's stopped and all servers show zero counters again

**Comment by JamyDev** [comment] 2015-12-28 18:42
Yes, this is currently the case as we had to disable our statistics engine. After we fix it it'll come back :)

**Comment by Antariano** [comment] 2015-12-30 14:21
Not a bug, closing. We need a status page @JamyDev

**Closed as completed** 2016-01-02 13:17 UTC
Labels: bug
