### ISSUE TITLE
Ram cpu etc statistics

### ISSUE THREAD

**Issue by Helomi** [SpaceCP/Bugs#41] opened 2015-12-18 18:51 UTC
Hello, i have problem with ram cpu etc statistics.
See screenshot (all servers)
https://ctrlv.cz/vmDh

**Comment by jithatsonei** [comment] 2015-12-18 19:26
Duplicate of #8 

You should read https://forums.spacecp.net/topic/322/known-bugs-in-spacecp and/or look at the open issues before opening a new one :)

**Comment by Antariano** [comment] 2015-12-18 19:28
Duplicate of #8

**Closed as completed by Antariano** 2015-12-18 19:28 UTC
