### ISSUE TITLE
[Panel/Daemon] Chat Error

### ISSUE THREAD

**Issue by jonyroda97** [SpaceCP/Bugs#16] opened 2015-12-12 20:16 UTC
http://pastebin.com/zfFqjR1j

https://gyazo.com/cd0ae447caf6a5ce2b6bf6a9234bec3a

**Comment by MiniDigger** [comment] 2015-12-12 20:42
the first error is caused by your inoffical essentials version
the duplicated messages were fixed in build 4, shou should update houston

**Comment by JamyDev** [comment] 2015-12-13 17:29
Going to close this, let me know if the double messages are still there.

**Closed as completed by JamyDev** 2015-12-13 17:29 UTC
