### ISSUE TITLE
RAM/CPU Display in right upper corner

### ISSUE THREAD

**Issue by renzfl** [SpaceCP/Bugs#165] opened 2016-02-29 21:20 UTC
Hello,
the RAM and CPU Display in the right upper corner only show's "0" for me. The displays on the dashboard work perfectly. I'm using Google Chrome, my Daemon runs on a windows server. (Spigot Mod for Minecraft)

![issue](https://cloud.githubusercontent.com/assets/10654554/13409281/8f90ed6c-df32-11e5-8c86-cc584027e96d.PNG)

**Comment by JamyDev** [comment] 2016-02-29 21:29
Duplicate of #162

**Closed as completed by JamyDev** 2016-02-29 21:29 UTC
