### ISSUE TITLE
Servers start on daemon shutdown

### ISSUE THREAD

**Issue by Willsr71** [SpaceCP/Bugs#135] opened 2016-01-17 06:08 UTC
Servers start up if they were off when the daemon is stopped. (stopped using the window button, not killed via task manager).

OS: Windows Server 2012 R2
Game: Minecraft
Mod: Bukkit, Vanilla, Custom

**Comment by tlaundal** [comment] 2016-01-17 14:39
I am not quite sure I understand this report correctly, but seems like a duplicate of #72

**Closed as completed** 2016-01-17 14:39 UTC
