### ISSUE TITLE
New 1.9 error

### ISSUE THREAD

**Issue by faneQ123** [SpaceCP/Bugs#167] opened 2016-03-02 18:21 UTC
[18:21:28 WARN]: [Houston] Task #387 for Houston v1.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at net.xereo.houston.bukkit.events.PlayerEvents.poll(PlayerEvents.java:98) ~[?:?]
at net.xereo.houston.java.events.PropertyEventManager.run(PropertyEventManager.java:65) ~[?:?]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[Houston] Connection daemon <-> Bukkit closed.

**Comment by JamyDev** [comment] 2016-03-02 18:22
Dupe of #166 please check the other issues before reposting the same

**Closed as completed** 2016-03-02 18:23 UTC

**Comment by faneQ123** [comment] 2016-03-02 18:25
Already updated. I red that post , downlaoded the update or patch , still getting this error
