### ISSUE TITLE
Front End Text Field

### ISSUE THREAD

**Issue by TheBloodHound** [SpaceCP/Bugs#27] opened 2015-12-13 23:51 UTC
At times, textfields' words such as Username, Email, Password, Host, Name, etc. sometimes don't go up above the text inputted so sometimes it would show (for example) Email overlapping email@example.com.

**Comment by MiniDigger** [comment] 2015-12-14 10:54
Could you provide screenshots and your browser and os version?

**Comment by TheBloodHound** [comment] 2015-12-14 20:42
I don't have screenshots at the moment but I am using Safari Version 9.0 on Mac OS X El Capitan Version 10.11

**Comment by JamyDev** [comment] 2015-12-14 23:33
When this happens, are they yellow too?

**Comment by TheBloodHound** [comment] 2015-12-15 00:27
No. Although I do remember I was switching between the website and another window.

**Comment by Antariano** [comment] 2015-12-18 19:30
Please provide screenshot and steps to reproduce so we can fix the issue.

**Comment by TheBloodHound** [comment] 2015-12-18 20:58
Okay, if it happens again I will be sure to take screenshots.

**Comment by Antariano** [comment] 2015-12-18 23:18
Closing for now. Will open if it happens again.

**Closed as completed by Antariano** 2015-12-18 23:18 UTC

**Comment by TheBloodHound** [comment] 2015-12-19 03:46
http://prntscr.com/9fxhvf It happened.

**Comment by TheBloodHound** [comment] 2015-12-19 03:48
I found out how to make it happen: I click on the input box, switch to another tab, and come back. http://prntscr.com/9fxi97 I did it with all of these using the method provided.

**Comment by MiniDigger** [comment] 2015-12-19 10:46
Can't reproduce on Chrome 47, Firefox 42 (Win10) and Chrome on Android (47 on CM12.1 5.1.1)
Could be a safari problem.
While testing I noticed something related: when Chrome tries to insert my password into the field the same glitch occurs. It is fixed by pressing somewhere on the site (i pressed to logo) https://gyazo.com/fa00d2340a1b6d69f30b40f4b6314144
