### ISSUE TITLE
Player Avatar not displayed

### ISSUE THREAD

**Issue by incognitojam** [SpaceCP/Bugs#77] opened 2015-12-29 11:11 UTC
It appears that the OPs section of the server console does not seem to be loading player avatars correctly.

![Operator Image](https://i.imgur.com/f4AyYUJ.png)

Right-clicking any of the images and selecting 'Copy URL' gives the same broken URL: https://crafatar.com/avatars/spacecp-minecraft-players-bukkit-dashboard-widget-bukkit-addon-directive?size=24. It appears that the usernames aren't actually being specified when creating these images programmatically.

![Broken URL](https://i.imgur.com/LlCkYoy.png)

Hopefully this can be fixed!

**Comment by Antariano** [comment] 2015-12-30 13:36
Good catch :) fixing

**Comment by Antariano** [comment] 2015-12-30 16:47
Fixed in build 7

**Comment by tlaundal** [comment] 2016-01-02 14:26
Could not reproduce on Firefox

**Closed as completed** 2016-01-04 15:33 UTC
Labels: bug, addon, fixed-but-not-deployed
