### ISSUE TITLE
Mod Mismatch

### ISSUE THREAD

**Issue by wolfiepawz** [SpaceCP/Bugs#155] opened 2016-02-16 13:18 UTC
https://pchard.gyazo.com/e161410b0ad73fe5f3abba6463e76313

```
We detected that your server config is set to custom but is running bukkit.
Would you like to switch the config to use bukkit instead?
Note that some panel features might not work if you keep it on bukkit
```

Clicking "Keep Using Custom" OR "Switch Config to Bukkit" doesn't work.

Using kCauldron.

**Comment by tlaundal** [comment] 2016-02-16 13:22
This is a duplicate of issue #80. 
Please search before you post.

**Closed as completed by tlaundal** 2016-02-16 13:22 UTC
