### ISSUE TITLE
Character codes/colors not supported in the server motd

### ISSUE THREAD

**Issue by qckcat** [SpaceCP/Bugs#56] opened 2015-12-21 01:13 UTC
You cannot use the Minecraft character code (& or §) nor the proper formatting code \u00A74 (and other variants).

Steps to recreate:
1. Open settings menu for the server you are attempting to edit.
2. Select configs tab.
3. Attempt to create a colored motd using any of the aforementioned options.

Other issues present: I believe that hard editing the file is overwritten by your last chosen "config menu" option; therefore you cannot create your motd in the server.properties file.

If you do, it leaves the error of incorrect formatting.

**Comment by JamyDev** [comment] 2015-12-21 09:11
Duplicate of #26

**Closed as completed by JamyDev** 2015-12-21 09:11 UTC
