### ISSUE TITLE
Spigot change player game mode does not notify

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#46] opened 2015-12-19 12:40 UTC
when changing the player game mode for a spigot 1.8.8 server, the game mode does actually change but the player receives no notification of the event and nothing appears in the console logs.

vanilla minecraft works fine in this regard.

in case it's related, i also saw a ticket open for "cannot op user in spigot". i don't know if the cause/effect is related in any way.

**Comment by MiniDigger** [comment] 2015-12-19 12:53
Copied from #23:
I would guess that this is intended. On vanilla there is not plugin. So houston uses the vanilla commands and that's where the message come from. On bukkit, we got a houston plugin which can do things silently. 
If I am right I would vote for some kind of logging of the houstonbukkit plugin to avoid confusion.
Some confirmation from @narrowtux or @JamyDev would be appreciated.

**Comment by narrowtux** [comment] 2015-12-19 15:29
Yes, this works as intended. On vanilla, we can only use command which do notify the player about the change, which we have no influence on.

**Comment by narrowtux** [comment] 2015-12-19 15:33
@JamyDev can be closed.

**Comment by Antariano** [comment] 2015-12-19 15:40
Closing. As a note, if you still want messages you can use the scheduler.

**Closed as completed by Antariano** 2015-12-19 15:40 UTC
