### ISSUE TITLE
Not showing chat or entered commands, cpu and ram use at 0% when server is running

### ISSUE THREAD

**Issue by ghost** [SpaceCP/Bugs#92] opened 2016-01-01 18:05 UTC
The server started up fine, the ram and cpu are at 0%, the chat and commands don't show up. using chrome on a mac.

**Comment by ghost** [comment] 2016-01-01 18:07
player count is 0 when players are on the server.

**Comment by tlaundal** [comment] 2016-01-02 14:44
The player count is a dupe of issue #76.

We need some more info to fix this, please answer the following questions:

What server are you running? Vanilla, Bukkit, Spigot? What version?
Where does the chat and commands not show up? Where do they show up (in game, in houston/daemon output, in console on the panel, in chat on the panel)?

I was not able to reproduce chat or commands not showing up. (Except for commands in vanilla, which doesn't show in log/console/houston output, because MC doesn't print them).
I was able to reproduce RAM and CPU as being at 0% in the top right corner.

For the future, please create one issue per issue/bug you are experiencing.

**Comment by ghost** [comment] 2016-01-02 15:18
We are running a spigot server, 1.8.8, the side menu, we can chat in game
but it does not show up in the chat on the panel.

**Comment by Forge-Media** [comment] 2016-01-02 15:43
Also experiencing this:
Spigot-1.8.8 (No Plugins) (Using [PM2](https://github.com/Unitech/pm2) instead of Screen on CentOS 7 VPS) 

Chat however does show up for me and commands seem to be working fine such as OPing players, but the players widget does not show anything.

![injhkbv](https://cloud.githubusercontent.com/assets/7041755/12074956/9ea7008c-b167-11e5-9e09-b97f8594af85.jpg)

**Comment by ghost** [comment] 2016-01-02 15:49
I use screen to keep houston running after I close my ssh connection,
should I be using something else?

**Comment by ghost** [comment] 2016-01-02 15:50
I am now also getting, No response from analytics server. Seek support on
our Support Forum https://forums.spacecp.net/category/23/support on both
ram and cpu.

**Comment by tlaundal** [comment] 2016-01-02 17:07
Players not showing up in the players widget is tracked in #76, and will be fixed in the next build. 

We are aware of analytics server being down and working on it. 

Both screen and PM2 should work fine for running Houston, and I believe it isn't related to the problem. 

So the issue is that chat does not show up in the chat side panel. Could you check in the plugin list that HoustonBukkit is running, and paste a log of your server when you start it, chat a bit and then stop it?

**Comment by Antariano** [comment] 2016-01-02 17:18
As per the readme of this repo

> One bug per issue please! Don't create lists of bugs in one issue.

Closing.

**Closed as completed by Antariano** 2016-01-02 17:18 UTC
