### ISSUE TITLE
Password Changing Save don´t work

### ISSUE THREAD

**Issue by jamatut** [SpaceCP/Bugs#178] opened 2016-03-12 15:58 UTC
Password changing save don´t work
Area : Acc. Settings 
Browser : Google Chrome 48.0.2564.116 m (64-bit)
Operating System : pc: Windows daemon ubunuto 14
when clicking save nothing happens (no error in console)

**Comment by Willsr71** [comment] 2016-03-12 19:12
Duplicate of #156

**Closed as completed** 2016-03-21 17:10 UTC
