### ISSUE TITLE
Something idk what this is?

### ISSUE THREAD

**Issue by StealWonders** [SpaceCP/Bugs#200] opened 2016-04-19 19:44 UTC
root@c01b14-4:/home/louisd/spacecp# node houston start
info: [bootstrap] Checking module existence...
info: [bootstrap] Module check completed.
info: Starting Houston (Build: 265)
info: info: [wrapper] Checking for updates...
info: info: [wrapper] Houston is up to date!
info: Checking Houston integrity...
info: Integrity check complete!
info: Checking dependencies for houston_game_minecraft

/home/louisd/spacecp/addons/houston_game_minecraft/MinecraftServer.js:82
    $server.api = Houston.apiManager.addSection(`server:${$server.id}`, "minec
                                                ^
failed to require "/home/louisd/spacecp//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/home/louisd/spacecp/houston.js:4:212)
    at b (/home/louisd/spacecp/houston.js:4:895)
    at /home/louisd/spacecp/houston.js:4:17010
    at /home/louisd/spacecp/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15) Error: failed to require "/home/louisd/spacecp//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/home/louisd/spacecp/houston.js:4:212)
    at b (/home/louisd/spacecp/houston.js:4:895)
    at /home/louisd/spacecp/houston.js:4:17010
    at /home/louisd/spacecp/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15)
    at c (/home/louisd/spacecp/houston.js:4:232)
    at b (/home/louisd/spacecp/houston.js:4:895)
    at /home/louisd/spacecp/houston.js:4:17010
    at /home/louisd/spacecp/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15)
info: Houston will now shut down...
19 Apr 21:42:36 - uncaughtException: fcd0b57c1d3c498bb4e300756caab317
info: Houston exiting.

**Comment by Willsr71** [comment] 2016-04-19 19:47
/home/louisd/spacecp//addons/houston_game_minecraft/MinecraftServer.js
spacecp//addons

that could be a problem

**Comment by StealWonders** [comment] 2016-04-19 19:49
What do you mean?

**Comment by StealWonders** [comment] 2016-04-19 19:49
How do I change this?

**Comment by Willsr71** [comment] 2016-04-19 19:50
It is probably an issue with the panel and nothing you can do, but there is a double slash in the directory path which would break certain things, as shown.

**Comment by StealWonders** [comment] 2016-04-19 19:50
Yeah, why am I having this?

**Comment by StealWonders** [comment] 2016-04-19 19:51
Could I change the path?

**Comment by JamyDev** [comment] 2016-04-19 19:52
Dupe of #193 and #195, update nodejs to `> 4.0`
please use the search function prior to creating issues, thanks!

**Closed as completed by JamyDev** 2016-04-19 19:52 UTC

**Comment by JamyDev** [comment] 2016-04-19 19:56
Btw @Willsr71, double slash in a path just gets normalized. If there was an issue there it would have triggered an ENOENT.

**Comment by Willsr71** [comment] 2016-04-19 19:57
Ah ok, thanks for clarifying.
