### ISSUE TITLE
failed to require "/srv/spacecp-daemon//addons/houston_game_minecraft/MinecraftServer.js" from root

### ISSUE THREAD

**Issue by JonathanVil** [SpaceCP/Bugs#195] opened 2016-04-09 20:52 UTC
Hey, I am trying to start houston for the first time and I am getting this error. Please help. Thanks!

root@omgserv-37359:/srv/spacecp-daemon# node houston start
info: [bootstrap] Checking module existence...
info: [bootstrap] Module check completed.
info: Starting Houston (Build: 265)
info: info: [wrapper] Checking for updates...
info: info: [wrapper] Houston is up to date!
info: Checking Houston integrity...
info: Integrity check complete!
info: Checking dependencies for houston_game_minecraft

/srv/spacecp-daemon/addons/houston_game_minecraft/MinecraftServer.js:82
    $server.api = Houston.apiManager.addSection(`server:${$server.id}`, "minec
                                                ^
failed to require "/srv/spacecp-daemon//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/srv/spacecp-daemon/houston.js:4:212)
    at b (/srv/spacecp-daemon/houston.js:4:895)
    at /srv/spacecp-daemon/houston.js:4:17010
    at /srv/spacecp-daemon/houston.js:4:15536
    at ReaddirReq.Req.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:135:5)
    at ReaddirReq.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:89:22)
    at Object.oncomplete (fs.js:107:15) Error: failed to require "/srv/spacecp-daemon//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/srv/spacecp-daemon/houston.js:4:212)
    at b (/srv/spacecp-daemon/houston.js:4:895)
    at /srv/spacecp-daemon/houston.js:4:17010
    at /srv/spacecp-daemon/houston.js:4:15536
    at ReaddirReq.Req.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:135:5)
    at ReaddirReq.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:89:22)
    at Object.oncomplete (fs.js:107:15)
    at c (/srv/spacecp-daemon/houston.js:4:232)
    at b (/srv/spacecp-daemon/houston.js:4:895)
    at /srv/spacecp-daemon/houston.js:4:17010
    at /srv/spacecp-daemon/houston.js:4:15536
    at ReaddirReq.Req.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:135:5)
    at ReaddirReq.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:89:22)
    at Object.oncomplete (fs.js:107:15)
info: Houston will now shut down...
9 Apr 22:50:26 - uncaughtException: 7eb26f4bb2de458abd986e7f2be1bb14
info: Houston exiting.

**Comment by JamyDev** [comment] 2016-04-09 20:53
Duplicate of #193, install node v4 or higher

**Closed as completed by JamyDev** 2016-04-09 20:53 UTC
